# Generated by Django 3.2.16 on 2023-12-27 13:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'panel_registro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('dni', models.CharField(max_length=9, null=True)),
                ('telefono_contacto', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('anexo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('red', models.CharField(max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.CharField(max_length=100, null=True)),
                ('area1', models.CharField(max_length=100, null=True)),
                ('estado_soli', models.CharField(max_length=3, null=True)),
                ('cod_arch', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'panel_solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('doc_ide', models.CharField(max_length=9, null=True)),
                ('password', models.TextField()),
                ('telefono_contacto', models.CharField(max_length=10)),
                ('anexo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('area', models.CharField(max_length=5)),
                ('id_red', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'panel_user',
                'ordering': ['id'],
            },
        ),
    ]
