# Generated by Django 4.1.5 on 2023-01-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='panel_user',
        ),
    ]
