# Generated by Django 3.2.16 on 2023-04-11 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_solicitud_red'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),                
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'panel_registros',
                'ordering': ['id'],
            },
        ),
    ]
