# Generated by Django 3.2.16 on 2023-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_migration_registros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'panel_registro',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Registros',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
