# Generated by Django 3.2.16 on 2023-04-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20230411_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado_soli',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterModelTable(
            name='registro',
            table='panel_registros',
        ),
    ]
