# Generated by Django 3.2.16 on 2023-04-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20230412_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro',
            table='panel_registro',
        ),
    ]
